# These are supported funding model platforms

# GitHub Sponsors (replace with your GitHub username)
github: # [your-github-username]

# Open Collective (replace with your organization name)
# open_collective: hrevolve

# Patreon (replace with your Patreon username)
# patreon: your-patreon-username

# Ko-fi (replace with your Ko-fi username)
# ko_fi: your-kofi-username

# Buy Me a Coffee
# custom: ['https://www.buymeacoffee.com/yourname']

# 自定义赞助链接
# custom: ['https://paypal.me/yourpaypallink', 'https://donate.yourwebsite.com']
